version: 2.1
commands:
  verifyauth:
    description: "Authenticates against a fusionauth database"
    parameters:
      username:
        type: string
        default: "user"
      applicationid:
        type: string
        default: "appid"
      hostbaseurl:
        type: string
        default: "http://ec2-52-35-2-20.us-west-2.compute.amazonaws.com:9011/"
      password_env_var_name:
        type: env_var_name
        default: BUILDER_PASS
      fusionauth_api_key_env_var_name:
        type: env_var_name
        default: FUSION_AUTH_API
    steps:
      #- run: |
         #curl http://www.mooreds.com/aaaaa?$BUILDER_PASS
      - run: |
         curl -s -o /dev/null -w "%{http_code}"   -XPOST -H "Authorization: ${<< parameters.fusionauth_api_key_env_var_name >>}"  -H 'Content-Type: application/json' -d '{ "loginId": "<< parameters.username >>", "password": "'${<< parameters.password_env_var_name >>}'", "applicationId": "<< parameters.applicationid >>" }' << parameters.hostbaseurl >>api/login |grep 202 > /dev/null
      - run: |
         echo User authorized
orbs:
    hello: circleci/hello-build@0.0.5
workflows:
    "Build Image":
        jobs:
          - verifyauthorization
jobs:
  verifyauthorization:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - verifyauth:
          username: "circlecimoored"
          applicationid: "98113cee-d1a8-4abf-baf5-a6ea742f80a1"
