version: 2.1
commands:
  verifyauth:
    description: "Authenticates against a fusionauth database"
    parameters:
      username:
        type: string
        default: "World"
      password:
        type: string
        default: "World"
    steps:
      - run: |
         echo hello << parameters.username >>
      - run: |
         curl https://www.yahoo.com
orbs:
    hello: circleci/hello-build@0.0.5
workflows:
    "Hello Workflow":
        jobs:
          - myjob
jobs:
  myjob:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - verifyauth:
          username: "circlecimooreds"
