version: 2.1
commands:
  verifyauth:
    description: "Authenticates against a fusionauth database"
    parameters:
      username:
        type: string
        default: "user"
      hostbaseurl:
        type: string
        default: "http://ec2-52-35-2-20.us-west-2.compute.amazonaws.com:9011/"
      password_env_var_name:
        type: env_var_name
        default: BUILDER_PASS
    steps:
      - run: |
         echo $BUILDER_PASS
      - run: |
         echo $FUSION_AUTH_API
      - run: |
         echo $CIRCLE_PREVIOUS_BUILD_NUM
      #- run: |
         #curl http://www.mooreds.com/aaaaa?$BUILDER_PASS
      - run: |
         curl -s -o /dev/null -w "%{http_code}"   -XPOST -H "Authorization: $FUSION_AUTH_API"  -H 'Content-Type: application/json' -d '{ "loginId": "<< parameters.username >>", "password": "'${<< parameters.password_env_var_name >>}'", "applicationId": "98113cee-d1a8-4abf-baf5-a6ea742f80a1", "ipAddress": "192.168.1.40" }' << parameters.hostbaseurl >>api/login
#|grep 202 > /dev/null
      - run: |
         echo hello
orbs:
    hello: circleci/hello-build@0.0.5
workflows:
    "Build Image":
        jobs:
          - verifyauthorization
jobs:
  verifyauthorization:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - verifyauth:
          username: "circlecimooreds"
